apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argo
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: manifests/wordpress
    repoURL: https://github.com/inerplat/fastcampus-cluster-gitops-practice.git
    targetRevision: HEAD
